gText_Birch_Welcome::
	.string "...Mom?{PAUSE 25} What's my {COLOR RED}name{COLOR DARK_GRAY}?\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Test0\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Test1\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I remember how she laughed--{PAUSE 20} kindly.\p"
	.string "...$"

gText_Birch_BoyOrGirl::
	.string "Chose a form for your journey.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "I...{PAUSE 50} don't know,{PAUSE 10} my love.\p"
	.string "...\p"
	.string "We'll only know when you come of age\n"
	.string "age and climb {COLOR RED}Mt. Massive{COLOR DARK_GRAY}.\p"
	.string "...$"

gText_Birch_AreYouReady::
	.string "$"

